### ISSUE TITLE
Default value should be 'Initial value' and should stay empty when cleared

### ISSUE THREAD

**Issue by pjrundle** [wombat-co/otter#13]
With a text field, when using `default_value`, when the user empties the field the default value is saved again rather than an empty string.

You might want a block with a heading field to have some dummy copy as a default when the block is added, but also to be able to be deleted/empty if desired.

**Comment by bhallstein** [comment]
Tweaked for clarity, please correct again if I misunderstood!

As I see it — could be a separate prop such as `initial_value = "X"` or a second option e.g. `default_value = "X", `default_removable = true` or similar.

Probably the first option — as potentially there is a case for supporting _both_ initial value and default value on a field. (Default meaning what appears when empty.)
